name=input("Enter your name: ")
surname=input("Enter your surname: ")
age=input("Enter your age: ")
number=input("Enter your phone number: ")
print("Name:", name)
print("Surname:", surname)
print("Age:", age)
print("Phone Number:", number)